[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=64",
  "wheel",
  "conan==2.4.0",
  "numpy>=1.21.2,<2.0.0",
]

[tool.cibuildwheel]
build-frontend = "build"
test-command = "python {project}/test.py"

[tool.cibuildwheel.macos]
archs = ["auto64"]

[tool.cibuildwheel.linux]
archs = ["auto64"]
before-all = [
  "chmod +x {project}/linux_before_all.sh",
  "bash {project}/linux_before_all.sh",
]
repair-wheel-command = [
  "export LD_LIBRARY_PATH=/project/oiio_python/libs:$LD_LIBRARY_PATH",
  "auditwheel repair -w {dest_dir} {wheel}",
]

[tool.cibuildwheel.windows]
archs = ["auto64"]

# ===========================[ BLACK ]========================

[tool.black]
line_length = 120

# ===========================[ ISORT ]========================

[tool.isort]
line_length = 120
profile = "black"

# ===========================[ PYLINT ]========================

[tool.pylint.FORMAT]
max-line-length = 120

[tool.pylint.'MESSAGES CONTROL']
disable = [
  'missing-module-docstring',
  'missing-class-docstring',
  'missing-function-docstring',
  'line-too-long',
  'too-many-locals',
  'too-many-instance-attributes',
  'too-many-positional-arguments',
  'too-many-arguments',
  'too-few-public-methods',
  'too-many-branches',
  'duplicate-code',
  'fixme',
]
