name: Build Linux Wheels

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build ${{ matrix.linking }} wheels on ${{ matrix.distrib }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distrib: [manylinux, musllinux]
        linking: [dynamic, static]

    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ENVIRONMENT_PASS_LINUX: OIIO_STATIC CIBUILDWHEEL MUSLLINUX_BUILD
          MUSLLINUX_BUILD: ${{ matrix.distrib == 'musllinux' && '1' || '0' }}
          OIIO_STATIC: ${{ matrix.linking == 'static' && '1' || '0' }}
          CIBW_BUILD: ${{ matrix.distrib == 'manylinux' && '*manylinux_x86*' || '*musllinux_x86*' }}

        with:
          output-dir: wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name:  cibw-wheels-${{ matrix.distrib }}-${{ matrix.linking }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
